"""Playwright e2e tests for the Nightjar GitHub Action PR comment.

These tests verify that the PR comment markdown generated by shadow_ci.py
renders correctly as HTML — i.e. that all required sections are present
and the report structure is human-readable.

We use Playwright's page.set_content() to render the markdown as HTML
via a minimal Markdown-to-HTML conversion (no external dependencies),
then assert key text elements are present in the DOM.

Skipped automatically when playwright is not installed.

References:
- nightjar-upgrade-plan.md U5.3 (lines 661-676)
- nightjar/shadow_ci.py — format_pr_comment()
- GitHub Flavored Markdown table rendering
"""
from __future__ import annotations

import re

import pytest

from playwright.sync_api import sync_playwright


# ---------------------------------------------------------------------------
# Minimal Markdown → HTML (avoid adding markdown library dependency)
# ---------------------------------------------------------------------------

def _md_to_html(md: str) -> str:
    """Convert a subset of Markdown to HTML for Playwright rendering.

    Handles headings, bold, blockquotes, tables, code spans, and paragraphs.
    Good enough for smoke-testing the PR comment structure.
    """
    lines = md.split("\n")
    html_lines = []
    in_table = False

    for line in lines:
        # Headings
        if line.startswith("### "):
            html_lines.append(f"<h3>{line[4:]}</h3>")
        elif line.startswith("## "):
            html_lines.append(f"<h2>{line[3:]}</h2>")
        elif line.startswith("# "):
            html_lines.append(f"<h1>{line[2:]}</h1>")
        # Table separator row (---|---) — skip
        elif re.match(r"^\|[-| :]+\|$", line):
            in_table = True
            continue
        # Table row
        elif line.startswith("|") and line.endswith("|"):
            in_table = True
            cells = [c.strip() for c in line[1:-1].split("|")]
            html_lines.append(
                "<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>"
            )
        else:
            if in_table:
                html_lines.append("</table>")
                in_table = False
            # Blockquote
            if line.startswith("> "):
                html_lines.append(f"<blockquote>{line[2:]}</blockquote>")
            # List item
            elif line.startswith("- "):
                html_lines.append(f"<li>{line[2:]}</li>")
            # Empty line → paragraph break
            elif line.strip() == "":
                html_lines.append("<br>")
            else:
                html_lines.append(f"<p>{line}</p>")

    if in_table:
        html_lines.append("</table>")

    return (
        "<!DOCTYPE html><html><head>"
        "<meta charset='utf-8'>"
        "</head><body>"
        + "\n".join(html_lines)
        + "</body></html>"
    )


# ---------------------------------------------------------------------------
# Test data
# ---------------------------------------------------------------------------

_PASSING_REPORT = {
    "verified": True,
    "confidence_score": 92,
    "stages": [
        {"stage": 0, "name": "preflight", "status": "pass", "errors": []},
        {"stage": 1, "name": "deps", "status": "pass", "errors": []},
        {"stage": 2, "name": "schema", "status": "pass", "errors": []},
    ],
}

_FAILING_REPORT = {
    "verified": False,
    "confidence_score": 40,
    "stages": [
        {
            "stage": 0,
            "name": "preflight",
            "status": "fail",
            "errors": [
                {
                    "message": "SQL injection pattern detected in query()",
                    "counterexample": "query('; DROP TABLE users --')",
                }
            ],
        }
    ],
}


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

class TestPRCommentRendersStructuredReport:
    """PR comment HTML renders all required sections for passing and failing reports."""

    def test_pr_comment_renders_passing_report(self):
        """Playwright: passing report shows verified status and confidence score."""
        from nightjar.shadow_ci import format_pr_comment

        md = format_pr_comment(_PASSING_REPORT)
        html = _md_to_html(md)

        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(html)

            body_text = page.inner_text("body")

            assert "Nightjar Shadow CI Report" in body_text, (
                "PR comment must include report title"
            )
            assert "92" in body_text, "Confidence score 92 must appear"
            assert "verified" in body_text.lower() or "All invariants" in body_text, (
                "Passing status must be indicated"
            )
            browser.close()

    def test_pr_comment_renders_violations(self):
        """Playwright: failing report shows violation details in rendered HTML."""
        from nightjar.shadow_ci import format_pr_comment

        md = format_pr_comment(_FAILING_REPORT)
        html = _md_to_html(md)

        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(html)

            body_text = page.inner_text("body")

            assert "Nightjar Shadow CI Report" in body_text
            assert "SQL injection" in body_text, (
                "Violation message must appear in rendered comment"
            )
            assert "40" in body_text, "Score 40 must appear in failing report"
            browser.close()

    def test_pr_comment_stage_table_present(self):
        """Playwright: stage summary table rows are present in rendered HTML."""
        from nightjar.shadow_ci import format_pr_comment

        md = format_pr_comment(_PASSING_REPORT)
        html = _md_to_html(md)

        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(html)

            body_text = page.inner_text("body")

            # Stage names must appear
            assert "preflight" in body_text, "preflight stage must appear in table"
            assert "deps" in body_text, "deps stage must appear in table"
            browser.close()

    def test_pr_comment_non_blocking_footer_present(self):
        """Playwright: non-blocking shadow CI disclaimer appears in comment."""
        from nightjar.shadow_ci import format_pr_comment

        md = format_pr_comment(_PASSING_REPORT)
        html = _md_to_html(md)

        with sync_playwright() as pw:
            browser = pw.chromium.launch(headless=True)
            page = browser.new_page()
            page.set_content(html)

            body_text = page.inner_text("body")

            assert "non-blocking" in body_text.lower() or "Shadow CI" in body_text, (
                "Non-blocking disclaimer must appear in PR comment footer"
            )
            browser.close()
