"""GitNexus blast radius warnings before code regeneration.

Before any symbol is regenerated by nightjar build, this hook queries the
GitNexus knowledge graph to determine how many other modules depend on that
symbol. If the blast radius is above a threshold, it warns the developer.

Pipeline:
    nightjar build payment.py
    → check_blast_radius("payment.deduct")
    → BlastRadiusResult(dependents=3, risk="HIGH", is_high_risk=True)
    → warn_before_regeneration() → True → "Continue? [Y/n]"

References:
- nightjar-upgrade-plan.md U5.2 (lines 640-659)
- GitNexus CLI: `npx gitnexus impact <target> --direction upstream`
- CLAUDE.md: "MUST run impact analysis before editing any symbol"
"""
from __future__ import annotations

import json
import subprocess
from dataclasses import dataclass, field
from typing import Optional

# Symbols whose upstream dependent count exceeds this are flagged HIGH risk.
_DEFAULT_THRESHOLD = 3

# Risk levels from GitNexus that always trigger a warning regardless of count.
_HIGH_RISK_LEVELS = {"HIGH", "CRITICAL"}


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

@dataclass
class BlastRadiusResult:
    """Result of a GitNexus upstream impact analysis for one symbol.

    Attributes:
        symbol_name: The queried symbol (e.g. ``payment.deduct``).
        dependents_count: Total upstream dependent symbols found.
        affected_modules: Module names that depend on this symbol.
        risk: GitNexus risk level string (LOW / MEDIUM / HIGH / CRITICAL).
        is_high_risk: True if the developer should be warned before proceeding.
    """

    symbol_name: str
    dependents_count: int = 0
    affected_modules: list[str] = field(default_factory=list)
    risk: str = "LOW"
    is_high_risk: bool = False


# ---------------------------------------------------------------------------
# CLI call + JSON parsing
# ---------------------------------------------------------------------------

def _run_gitnexus_impact(symbol_name: str) -> Optional[dict]:
    """Invoke ``npx gitnexus impact <symbol>`` and return parsed JSON.

    Returns:
        Parsed dict on success, or ``None`` if the CLI is unavailable or
        fails to produce valid JSON.
    """
    try:
        proc = subprocess.run(
            ["npx", "gitnexus", "impact", symbol_name, "--direction", "upstream"],
            capture_output=True,
            text=True,
            timeout=15,
            encoding="utf-8",
            errors="replace",
        )
        return json.loads(proc.stdout)
    except (FileNotFoundError, subprocess.TimeoutExpired):
        # Tool not installed or timed out — safe default: no warning.
        return None
    except (json.JSONDecodeError, ValueError):
        return None


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def check_blast_radius(
    symbol_name: str,
    threshold: int = _DEFAULT_THRESHOLD,
) -> BlastRadiusResult:
    """Query GitNexus for the upstream blast radius of a symbol.

    Args:
        symbol_name: Fully-qualified symbol name, e.g. ``payment.deduct``.
        threshold: Dependent count above which the result is flagged
                   as high-risk (default 3).

    Returns:
        :class:`BlastRadiusResult` — never raises; safe defaults on failure.
    """
    data = _run_gitnexus_impact(symbol_name)

    # Tool unavailable or symbol not found → safe default, don't block build.
    if data is None or "error" in data:
        return BlastRadiusResult(
            symbol_name=symbol_name,
            dependents_count=0,
            affected_modules=[],
            risk="LOW",
            is_high_risk=False,
        )

    impacted_count: int = data.get("impactedCount", 0)
    risk: str = data.get("risk", "LOW")
    affected_modules: list[str] = data.get("affected_modules", [])

    # Treat direct dependents as the primary count for threshold comparison.
    direct: int = data.get("summary", {}).get("direct", 0)
    compare_count = max(impacted_count, direct)

    is_high_risk = (risk in _HIGH_RISK_LEVELS) or (compare_count > threshold)

    return BlastRadiusResult(
        symbol_name=symbol_name,
        dependents_count=compare_count,
        affected_modules=affected_modules,
        risk=risk,
        is_high_risk=is_high_risk,
    )


def warn_before_regeneration(
    symbol_name: str,
    threshold: int = _DEFAULT_THRESHOLD,
) -> bool:
    """Return True if the developer should be warned before regenerating symbol.

    Intended for integration into the nightjar build pipeline: call this
    before regenerating any function and prompt the user if it returns True.

    Args:
        symbol_name: Symbol about to be regenerated.
        threshold: Forwarded to :func:`check_blast_radius`.

    Returns:
        ``True`` if blast radius is high and a warning should be displayed.
    """
    result = check_blast_radius(symbol_name, threshold=threshold)
    return result.is_high_risk


def format_blast_radius_warning(result: BlastRadiusResult) -> str:
    """Format a human-readable blast radius warning message.

    Args:
        result: The :class:`BlastRadiusResult` from :func:`check_blast_radius`.

    Returns:
        A warning string suitable for display in the CLI or PR comment.
    """
    module_list = ", ".join(result.affected_modules) if result.affected_modules else "none"
    return (
        f"[GitNexus] WARNING: Regenerating '{result.symbol_name}' has a "
        f"{result.risk} blast radius — {result.dependents_count} dependent(s) "
        f"affected: {module_list}. "
        f"Verify downstream modules before proceeding."
    )
