"""Test oracle lifting — assert statements → card.md invariants.

Task U2.2: Scan test files for assert statements → automatically lift
them into candidate postconditions for .card.md specs.

Reference: arxiv:2601.12845 — 98.2% success rate lifting test assertions
into postconditions for formal verification (TestDafny110 dataset).

Pipeline:
  test_file.py (asserts) → extract_asserts → lift_to_invariants (LLM)
      → LiftedInvariant list → lift_to_card → .card.md

All LLM calls use litellm [REF-T16] with the provided model identifier.
NIGHTJAR_MODEL env var is respected by the CLI wrapper (nightjar auto).

License: MIT
"""

from __future__ import annotations

import ast
import os
from dataclasses import dataclass, field
from pathlib import Path

import litellm


# ── Constants ─────────────────────────────────────────────────────────────────

_GENERATION_TEMPERATURE = 0.1
_MAX_TOKENS = 128

_SYSTEM_PROMPT = """\
You are a software specification expert.
Convert the given Python assert expression into a concise natural-language invariant.

RULES:
1. Write one sentence describing what must always be true
2. Use plain English — no Python syntax
3. Be specific about what is being constrained
4. Do NOT include phrases like "the assert checks that" — just state the invariant

Example:
Assert: result.balance >= 0
Output: balance is always non-negative after any operation

Example:
Assert: result.receipt is not None
Output: successful operations always return a non-null receipt
"""

_CARD_SECTION_HEADER = "\n\n## Lifted Invariants\n\n<!-- oracle-lifted: auto-generated from test assertions -->\n"


# ── LiftedInvariant ───────────────────────────────────────────────────────────


@dataclass
class LiftedInvariant:
    """A test assertion lifted to a natural-language invariant.

    Produced by oracle_lifter and written into .card.md specs.
    Reference: arxiv:2601.12845 — test oracle lifting.
    """

    assert_expr: str         # Original Python assert expression
    nl_statement: str        # NL invariant generated by LLM
    tier: str = "property"   # card.md tier (property / example / formal)


# ── extract_asserts ───────────────────────────────────────────────────────────


def extract_asserts(source: str) -> list[str]:
    """Extract assert test expressions from Python source via AST.

    Walks the full AST — finds every ast.Assert node and returns the
    string representation of its test expression. The assert message
    (second argument) is ignored.

    Args:
        source: Python source code string (a test file).

    Returns:
        List of assert expression strings, in source order.
    """
    if not source.strip():
        return []

    try:
        tree = ast.parse(source)
    except SyntaxError:
        return []

    exprs: list[str] = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Assert):
            exprs.append(ast.unparse(node.test))
    return exprs


# ── lift_to_invariants ────────────────────────────────────────────────────────


def lift_to_invariants(
    assert_exprs: list[str],
    model: str,
) -> list[LiftedInvariant]:
    """Convert assert expressions to NL invariants via LLM.

    Makes one litellm call per assert expression. On LLM error, falls
    back to a stub NL statement derived from the assert text so the
    pipeline never raises.

    Args:
        assert_exprs: List of Python assert expression strings.
        model:        litellm model identifier.

    Returns:
        List of LiftedInvariant, same length and order as input.
    """
    if not assert_exprs:
        return []

    results: list[LiftedInvariant] = []
    for expr in assert_exprs:
        nl = _llm_lift(expr, model)
        results.append(LiftedInvariant(assert_expr=expr, nl_statement=nl))
    return results


def _llm_lift(assert_expr: str, model: str) -> str:
    """Call litellm to convert one assert expression to NL invariant."""
    user_prompt = f"Assert: {assert_expr}\nOutput:"
    try:
        response = litellm.completion(
            model=model,
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": user_prompt},
            ],
            temperature=_GENERATION_TEMPERATURE,
            max_tokens=_MAX_TOKENS,
        )
        return (response.choices[0].message.content or "").strip()
    except Exception:
        # Graceful fallback — never block the pipeline
        return f"expression holds: {assert_expr}"


# ── lift_oracle_file ──────────────────────────────────────────────────────────


def lift_oracle_file(source_path: Path, model: str) -> list[LiftedInvariant]:
    """Read a test file, extract asserts, and lift to NL invariants.

    Convenience wrapper around extract_asserts + lift_to_invariants.

    Args:
        source_path: Path to a Python test file.
        model:       litellm model identifier.

    Returns:
        List of LiftedInvariant for all asserts in the file.

    Raises:
        FileNotFoundError: if source_path does not exist.
    """
    if not source_path.exists():
        raise FileNotFoundError(f"Test file not found: {source_path}")

    source = source_path.read_text(encoding="utf-8")
    assert_exprs = extract_asserts(source)
    if not assert_exprs:
        return []
    return lift_to_invariants(assert_exprs, model=model)


# ── lift_to_card ──────────────────────────────────────────────────────────────


def lift_to_card(
    invariants: list[LiftedInvariant],
    card_path: Path,
) -> int:
    """Append lifted invariants to a .card.md file.

    Adds a '## Lifted Invariants' section with each invariant's NL
    statement and the source assert expression it was derived from.
    Creates the file if it does not exist. Does nothing if invariants
    is empty.

    Args:
        invariants: Lifted invariants to append.
        card_path:  Path to target .card.md file.

    Returns:
        Number of invariants written (0 if empty).
    """
    if not invariants:
        return 0

    lines: list[str] = [_CARD_SECTION_HEADER]
    for li in invariants:
        lines.append(f"- tier: {li.tier}\n")
        lines.append(f"  statement: \"{li.nl_statement}\"\n")
        lines.append(f"  source: `{li.assert_expr}`\n")
        lines.append("\n")

    section = "".join(lines)

    existing = card_path.read_text(encoding="utf-8") if card_path.exists() else ""
    card_path.write_text(existing + section, encoding="utf-8")

    return len(invariants)
